# Generated by Django 5.0.4 on 2024-05-07 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_historicalperformance_average_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 18, 6, 12, 220721, tzinfo=datetime.timezone.utc)),
        ),
    ]
